### ISSUE TITLE
Add how to abort a merge

### ISSUE THREAD

**Issue by garster** [arit-ucsb/Arit.Git.CheatSheet#3]
git merge --abort

**Comment by NightWatchman** [comment]
![giphy-downsized-large 1](https://cloud.githubusercontent.com/assets/390131/25057027/848cf4ce-2121-11e7-93e4-b24b1ffd5277.gif)

**Comment by UCSBMike** [comment]
@garster - there is also this:

    git merge --abort
    # or
    git reset --merge

Should I add both? I ask because I haven't tried the other one.
